
import java.awt.Color;
import java.awt.Component;
import java.sql.*;
import java.util.Vector;
import java.sql.Date;
import java.time.LocalDate;
import java.util.logging.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author chizi
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    Color myNightBlue = new Color(34, 51, 80);
    Color myCharcuterie = new Color(179, 202, 214);
    Color myFadedBlue = new Color(154, 172, 192);
    Color myPrettyBlue = new Color(37, 91, 125);
    Color myPrussianBlue = new Color(0, 48, 73);
    Color mySevenSeas = new Color(51, 87, 110);
    Connection conn;
    PreparedStatement ps;
    private int id;
    
    public home(int index) {
        initComponents();
        id = index;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/todoapp", "root", "ChizimAwele-123.");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jPanel2.setVisible(false);
        jPanel4.setVisible(false);
        
        try {
            ps = conn.prepareStatement("select username from usertb where userid = ?");
            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
                jLabel1.setText("Welcome "+rs.getString("username"));
            }            
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error Occurred!");
        }
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addTaskButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        newtasklabel = new javax.swing.JLabel();
        newtasktxt = new javax.swing.JTextField();
        newduedatetxt = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        newduedatelabel = new javax.swing.JLabel();
        dateFormat = new javax.swing.JLabel();
        cancelNewTask = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        tasklabel = new javax.swing.JLabel();
        tasktxt = new javax.swing.JTextField();
        duedatetxt = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        duedatelabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        dateFormat1 = new javax.swing.JLabel();
        deleteButton1 = new javax.swing.JButton();
        cancelTask = new javax.swing.JLabel();
        newtasklabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(154, 172, 192));

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 48, 73));
        jLabel1.setText("Welcome Username ");

        jTable1.setBackground(new java.awt.Color(51, 81, 110));
        jTable1.setForeground(new java.awt.Color(154, 172, 192));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Task", "Created", "Due"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionForeground(new java.awt.Color(0, 65, 94));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTable1MouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        addTaskButton.setBackground(new java.awt.Color(179, 202, 214));
        addTaskButton.setFont(new java.awt.Font("Poor Richard", 1, 16)); // NOI18N
        addTaskButton.setForeground(new java.awt.Color(34, 51, 80));
        addTaskButton.setText("ADD TASK");
        addTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(154, 172, 192));

        jLabel3.setFont(new java.awt.Font("Mongolian Baiti", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(60, 65, 90));
        jLabel3.setText("NEW TASK ");

        jPanel3.setBackground(new java.awt.Color(105, 126, 147));

        newtasklabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        newtasklabel.setForeground(new java.awt.Color(34, 34, 59));
        newtasklabel.setText("Task:");

        newtasktxt.setBackground(new java.awt.Color(154, 168, 193));
        newtasktxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newtasktxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newtasktxtMouseExited(evt);
            }
        });

        newduedatetxt.setBackground(new java.awt.Color(154, 168, 193));
        newduedatetxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newduedatetxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newduedatetxtMouseExited(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(179, 202, 214));
        addButton.setFont(new java.awt.Font("Poor Richard", 1, 16)); // NOI18N
        addButton.setForeground(new java.awt.Color(34, 51, 80));
        addButton.setText("ADD");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addButtonMouseExited(evt);
            }
        });
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        newduedatelabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        newduedatelabel.setForeground(new java.awt.Color(34, 34, 59));
        newduedatelabel.setText("Due Date:");

        dateFormat.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        dateFormat.setForeground(new java.awt.Color(204, 204, 204));
        dateFormat.setText("yyyy-mm-dd");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(newtasklabel)
                        .addGap(33, 33, 33)
                        .addComponent(newtasktxt)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(newduedatelabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(dateFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(newduedatetxt)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 9, Short.MAX_VALUE)
                                .addComponent(addButton)
                                .addGap(90, 90, 90))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newtasklabel)
                    .addComponent(newtasktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(dateFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newduedatelabel)
                    .addComponent(newduedatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(addButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        cancelNewTask.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        cancelNewTask.setForeground(new java.awt.Color(60, 65, 90));
        cancelNewTask.setText("X");
        cancelNewTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelNewTaskMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cancelNewTask)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cancelNewTask, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(154, 172, 192));

        jLabel6.setFont(new java.awt.Font("Mongolian Baiti", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(60, 65, 90));
        jLabel6.setText("TASK ");

        jPanel5.setBackground(new java.awt.Color(105, 126, 147));

        tasklabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tasklabel.setForeground(new java.awt.Color(34, 34, 59));
        tasklabel.setText("Task:");

        tasktxt.setBackground(new java.awt.Color(154, 168, 193));
        tasktxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tasktxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tasktxtMouseExited(evt);
            }
        });

        duedatetxt.setBackground(new java.awt.Color(154, 168, 193));
        duedatetxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                duedatetxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                duedatetxtMouseExited(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(179, 202, 214));
        editButton.setFont(new java.awt.Font("Poor Richard", 1, 16)); // NOI18N
        editButton.setForeground(new java.awt.Color(34, 51, 80));
        editButton.setText("EDIT");
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editButtonMouseExited(evt);
            }
        });
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        duedatelabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        duedatelabel.setForeground(new java.awt.Color(34, 34, 59));
        duedatelabel.setText("Due Date:");

        deleteButton.setBackground(new java.awt.Color(179, 202, 214));
        deleteButton.setFont(new java.awt.Font("Poor Richard", 1, 16)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(34, 51, 80));
        deleteButton.setText("DELETE");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteButtonMouseExited(evt);
            }
        });
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        dateFormat1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        dateFormat1.setForeground(new java.awt.Color(204, 204, 204));
        dateFormat1.setText("yyyy-mm-dd");

        deleteButton1.setBackground(new java.awt.Color(179, 202, 214));
        deleteButton1.setFont(new java.awt.Font("Poor Richard", 1, 16)); // NOI18N
        deleteButton1.setForeground(new java.awt.Color(34, 51, 80));
        deleteButton1.setText("Mark as Completed");
        deleteButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteButton1MouseExited(evt);
            }
        });
        deleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(duedatelabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(duedatetxt))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(editButton)
                                .addGap(38, 38, 38)
                                .addComponent(deleteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(deleteButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tasklabel)
                        .addGap(33, 33, 33)
                        .addComponent(tasktxt))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(dateFormat1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 44, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tasklabel)
                    .addComponent(tasktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateFormat1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duedatelabel)
                    .addComponent(duedatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(deleteButton))
                .addGap(18, 18, 18)
                .addComponent(deleteButton1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        cancelTask.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        cancelTask.setForeground(new java.awt.Color(60, 65, 90));
        cancelTask.setText("X");
        cancelTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelTaskMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cancelTask)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel6)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cancelTask, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        newtasklabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        newtasklabel1.setForeground(new java.awt.Color(34, 34, 59));
        newtasklabel1.setText("Completed Tasks...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(newtasklabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(addTaskButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newtasklabel1)
                .addGap(27, 27, 27)
                .addComponent(addTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(940, 940, 940))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        jTable1.setBackground(myFadedBlue);
        jTable1.setForeground(myPrussianBlue);
    }//GEN-LAST:event_jTable1MouseEntered

    private void jTable1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseExited
        jTable1.setBackground(mySevenSeas);
        jTable1.setForeground(myCharcuterie);
    }//GEN-LAST:event_jTable1MouseExited

    private void addButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseEntered
        addButton.setBackground(myNightBlue);
        addButton.setForeground(myCharcuterie);
    }//GEN-LAST:event_addButtonMouseEntered

    private void addButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseExited
        addButton.setBackground(myCharcuterie);
        addButton.setForeground(myNightBlue);
    }//GEN-LAST:event_addButtonMouseExited

    private void newtasktxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newtasktxtMouseEntered
        newtasktxt.setBackground(Color.white);
        newtasktxt.setForeground(myNightBlue);
    }//GEN-LAST:event_newtasktxtMouseEntered

    private void newtasktxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newtasktxtMouseExited
        newtasktxt.setBackground(myPrettyBlue);
        newtasktxt.setForeground(myCharcuterie);
    }//GEN-LAST:event_newtasktxtMouseExited

    private void addTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskButtonActionPerformed
        jPanel2.setVisible(true);       
    }//GEN-LAST:event_addTaskButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String task = newtasktxt.getText();
        String duedate = newduedatetxt.getText();
        Date date = Date.valueOf(duedate);
        try {
            ps = conn.prepareStatement("insert into todotb(task, duedate, userid) values(?,?,?)");
            ps.setString(1, task);
            ps.setDate(2, date);
            ps.setInt(3, id);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Task Added to Todo List!");
            updateTable();
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error Occurred!");
        }
        newtasktxt.setText(null);
        newduedatetxt.setText(null);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelNewTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelNewTaskMouseClicked
        jPanel2.setVisible(false);
    }//GEN-LAST:event_cancelNewTaskMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
            int selectedIndex = jTable1.getSelectedRow();

            int confirmComplete = JOptionPane.showConfirmDialog(null, "Do you want to mark task \"" + dtm.getValueAt(selectedIndex, 0).toString() + "\" as complete?", "Confirmation", JOptionPane.YES_NO_OPTION);
            
            if(confirmComplete == JOptionPane.YES_OPTION){            
                ps = conn.prepareStatement("update todotb set task=?, duedate = ? where createddate=?");
                ps.executeUpdate();
            
                JOptionPane.showMessageDialog(this, "Task Marked as Completed!");
                updateTable();
            }else{
                jPanel4.setVisible(true);
                
                tasktxt.setText(dtm.getValueAt(selectedIndex, 0).toString());
                duedatetxt.setText(dtm.getValueAt(selectedIndex, 2).toString());
            }
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error Occurred!");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void tasktxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tasktxtMouseEntered
        newduedatetxt.setBackground(Color.white);
        newduedatetxt.setForeground(myNightBlue);
    }//GEN-LAST:event_tasktxtMouseEntered

    private void tasktxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tasktxtMouseExited
        newduedatetxt.setBackground(myPrettyBlue);
        newduedatetxt.setForeground(myCharcuterie);
    }//GEN-LAST:event_tasktxtMouseExited

    private void duedatetxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duedatetxtMouseEntered
        newduedatetxt.setBackground(Color.white);
        newduedatetxt.setForeground(myNightBlue);
    }//GEN-LAST:event_duedatetxtMouseEntered

    private void duedatetxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duedatetxtMouseExited
        newduedatetxt.setBackground(myPrettyBlue);
        newduedatetxt.setForeground(myCharcuterie);
    }//GEN-LAST:event_duedatetxtMouseExited

    private void editButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseEntered
        addButton.setBackground(myNightBlue);
        addButton.setForeground(myCharcuterie);
    }//GEN-LAST:event_editButtonMouseEntered

    private void editButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseExited
        addButton.setBackground(myCharcuterie);
        addButton.setForeground(myNightBlue);
    }//GEN-LAST:event_editButtonMouseExited

    private void deleteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseEntered
        addButton.setBackground(myNightBlue);
        addButton.setForeground(myCharcuterie);
    }//GEN-LAST:event_deleteButtonMouseEntered

    private void deleteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseExited
        addButton.setBackground(myCharcuterie);
        addButton.setForeground(myNightBlue);
    }//GEN-LAST:event_deleteButtonMouseExited

    private void cancelTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelTaskMouseClicked
        jPanel4.setVisible(false);
    }//GEN-LAST:event_cancelTaskMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        try {
            DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
            int selectedIndex = jTable1.getSelectedRow();

            String task = tasktxt.getText();
            String duedate = duedatetxt.getText();
            String timeid = dtm.getValueAt(selectedIndex, 1).toString();
            Timestamp createddate = Timestamp.valueOf(timeid);
            int confirmDelete = JOptionPane.showConfirmDialog(null, "Are you sure you want to edit this task?", "Warning", JOptionPane.YES_NO_OPTION);
            
            if(confirmDelete == JOptionPane.YES_OPTION){            
                ps = conn.prepareStatement("update todotb set task=?, duedate = ? where createddate=?");
                ps.setString(1, task);
                ps.setString(2, duedate);
                ps.setTimestamp(3, createddate);
                ps.executeUpdate();
            
                JOptionPane.showMessageDialog(this, "Task Updated!");
                updateTable();
                jPanel4.setVisible(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error Occurred!");
        }
        
        tasktxt.setText(null);
        duedatetxt.setText(null);
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
            int selectedIndex = jTable1.getSelectedRow();
            String timeid = dtm.getValueAt(selectedIndex, 1).toString();
            Timestamp createddate = Timestamp.valueOf(timeid);
        
            int confirmDelete = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this task?", "Warning", JOptionPane.YES_NO_OPTION);
            
            if(confirmDelete == JOptionPane.YES_OPTION){
                ps = conn.prepareStatement("delete from todotb where createddate=?");
                ps.setTimestamp(1, createddate);
                ps.executeUpdate();
            
                JOptionPane.showMessageDialog(this, "Task Deleted!");
                updateTable();
                jPanel4.setVisible(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error Occurred!");
        }
        
        tasktxt.setText(null);
        duedatetxt.setText(null);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void newduedatetxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newduedatetxtMouseExited
        newduedatetxt.setBackground(myPrettyBlue);
        newduedatetxt.setForeground(myCharcuterie);
    }//GEN-LAST:event_newduedatetxtMouseExited

    private void newduedatetxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newduedatetxtMouseEntered
        newduedatetxt.setBackground(Color.white);
        newduedatetxt.setForeground(myNightBlue);
    }//GEN-LAST:event_newduedatetxtMouseEntered

    private void deleteButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButton1MouseEntered

    private void deleteButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButton1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButton1MouseExited

    private void deleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButton1ActionPerformed

    private void updateTable() {
        int c;
        LocalDate when = LocalDate.now();
        Date date = Date.valueOf(when);
        TableCellRenderer renderer;
        try {
            ps = conn.prepareStatement("select * from todotb where userid = ?");
            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();
            ResultSetMetaData Rsmd = rs.getMetaData();
            c = Rsmd.getColumnCount();
            
            DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
            
            while (rs.next()) {
                Vector v1 = new Vector();
                
                for(int a=1; a<=c; a++){
                    v1.add(rs.getString("task"));
                    v1.add(rs.getTimestamp("createddate"));
                    v1.add(rs.getDate("duedate"));
                }
                dtm.addRow(v1);                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private int index;
            public void run() {
                new home(index).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addTaskButton;
    private javax.swing.JLabel cancelNewTask;
    private javax.swing.JLabel cancelTask;
    private javax.swing.JLabel dateFormat;
    private javax.swing.JLabel dateFormat1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteButton1;
    private javax.swing.JLabel duedatelabel;
    private javax.swing.JTextField duedatetxt;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel newduedatelabel;
    private javax.swing.JTextField newduedatetxt;
    private javax.swing.JLabel newtasklabel;
    private javax.swing.JLabel newtasklabel1;
    private javax.swing.JTextField newtasktxt;
    private javax.swing.JLabel tasklabel;
    private javax.swing.JTextField tasktxt;
    // End of variables declaration//GEN-END:variables
}
